### ISSUE TITLE
Where is the Database?

### ISSUE THREAD

**Issue by JattJames** [strubenstein/RubensteinBilling#1]
Can i know where is the Database?

**Comment by strubenstein** [comment]
That is an excellent question. It seems I did not include the SQL script to generate the database in the code. Sorry about that.

I will try to post it later today.

**Comment by strubenstein** [comment]
I posted scripts to generate the database in both SQL Server and MySQL.

Let me know if you have any questions or run into any issues.

Full disclosure -- I have not looked at this code in a long time. And I would definitely not re-write it the same way. But it definitely works.
